// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/towelong/egret"
	"github.com/towelong/egret/example/internal/pkg/config"
	"github.com/towelong/egret/example/internal/pkg/logger"
	"github.com/towelong/egret/example/internal/repo"
	"github.com/towelong/egret/example/internal/server"
	"github.com/towelong/egret/example/internal/service"
	"github.com/towelong/egret/example/internal/usecase"
)

// Injectors from wire.go:

func initApp(c *config.Config) *egret.App {
	zapLogger := logger.New()
	userRepo := repo.NewUserRepo(zapLogger)
	userUsecase := usecase.NewUserUsecase(userRepo, zapLogger)
	shopInterface := service.NewShopInterface(userUsecase, zapLogger)
	engine := server.NewHttpServer(shopInterface, zapLogger)
	app := newApp(c, engine)
	return app
}
