app:
  name: example
  version: 1.0.0
  addr: 8081
  timeout: 2
data:
  database:
    driver: mysql
    source: root:123456789@tcp(127.0.0.1:3306)/ns-shop?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    password:
    read_timeout: 0.2
    write_timeout: 0.2
